# Generated by Django 5.0.6 on 2024-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
    ]
